# Background

These are the files produced during a homework assignment of Coursera MOOC Developing Data Products from Johns Hopkins University, where students could pick any dataset, and should produce a web app hosted on SaaS platform from RStudio shinyapss.io.

The data set that I choose was from Kaggle Titanic Challenge, since this is a starting point for many Machine Learning enthusiasts.

The materials can be found in:

Web app: https://littlepony.shinyapps.io/Titanic/

GitHub Repo: https://github.com/littleponytin/DevDataProd

# Code for plots
ggplot 2 Library was used for the plotting. Here is the code for a static view of the default plot that is rendered on the web app:

``` {r code}
library(ggplot2)
trainData <- read.csv(url("http://s3-eu-west-1.amazonaws.com/dpadata/dataScience/train.csv"))
g <- ggplot(trainData, aes(Age, Pclass))
g + geom_point(aes(color=Sex)) + facet_grid(Survived ~.)
```

# Guidelines to reproduce locally
Guidelines to reproduce this project locally on your PC

To run locally this App on your computer you do NOT need to fork this repo. 
Please follow these instructions:

Install the necessary packages to run RStudio Shiny Server locally. Please view the well documented requirements in the getting started page: http://shiny.rstudio.com/articles/shinyapps.html

Run the following command in the RStudio:

runGitHub("DevDataProd", "littleponytin")


# For more information
For more information about the several MOOCs comprised in this Specialization, please visit: https://www.coursera.org/specialization/jhudatascience/

For more information about RStudio Shinyapps.io visit: http://shiny.rstudio.com/articles/shinyapps.html

For more information about Kaggle Titanic challenge visit: https://www.kaggle.com/c/titanic-gettingStarted